import type { Metadata } from "next"
import { Mulish } from "next/font/google"
import { ReactNode } from "react"
import "./globals.css"

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Music Player",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" className="bg-slate-950">
      <body className={`${mulish.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}